server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nasa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
nasa-api:
  key: 6tszvseadOVuAmL3spNTynQRcc0GHTKtgPeAXnCs
  base-url: https://api.nasa.gov
application:
  base-url: /planetary/apod